name: EntityLinkerEnv 
channels:
  - conda-forge
  - pytorch
dependencies:
  - transformers
    #- datasets
  - faiss-cpu
    #- geopandas
  - jarowinkler
  - numba
  - numpy
  - pandas
  - pynndescent
  - rapidfuzz
  - scikit-learn
  - scipy
  - setuptools
  - pytorch
  - tqdm
  - pytest
  - wandb
  - pip
  - pip:
    - datasketch
